spring.application.name=ai-service
server.port=8082

eureka.client.enabled=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}

spring.ai.openai.chat.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.model=openrouter/free