spring.application.name=ai-service
server.port=8082

eureka.client.enabled=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}

spring.ai.openai.chat.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.model=openrouter/free

# ===============================
# POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/studyai_ai
spring.datasource.username=studyai
spring.datasource.password=studyai123
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# PGVECTOR
# ===============================

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024

#Configuracion modelo embeddings
spring.ai.openai.embedding.model=liquid/lfm-2.5-embedding-350m:free
spring.ai.vectorstore.pgvector.dimensions=1024