spring.application.name=eureka-service

server.port=8100

eureka.instance.hostname=localhost

#Desactivar el modo de autoprotección en desarrollo
eureka.server.enable-self-preservation=false

eureka.client.register-with-eureka=false

# Evita que intente descargar el registro de servicios, ya que él es la fuente de la verdad
eureka.client.fetch-registry=false

#Opcional: Hacer que limpie instancias inactivas más rápido (cada 5 segundos)
eureka.server.eviction-interval-timer-in-ms=5000